#!/bin/bash

# Screenshot Creation Helper
# This script provides instructions for creating screenshots for the README

echo "📸 Screenshot Creation Guide for Dev Monitor"
echo "==========================================="
echo ""
echo "To create compelling screenshots for the README:"
echo ""
echo "1. 🚀 Start Dev Monitor:"
echo "   ./scripts/tasks.sh dev"
echo ""
echo "2. 📝 Add sample projects with descriptive names:"
echo "   - 'Personal Website' -> ~/projects/my-website"
echo "   - 'React Dashboard' -> ~/projects/dashboard-app"
echo "   - 'Python API Server' -> ~/projects/api-backend"
echo "   - 'Mobile App' -> ~/projects/flutter-app"
echo ""
echo "3. 📷 Take screenshots of:"
echo "   - Main window with project list"
echo "   - Add project modal"
echo "   - Edit project modal"
echo "   - Empty state (no projects)"
echo ""
echo "4. 🎨 Recommended screenshot settings:"
echo "   - Window size: 900x600 (default)"
echo "   - High DPI/Retina display preferred"
echo "   - Clean desktop background"
echo "   - Good lighting for screen capture"
echo ""
echo "5. 💾 Save screenshots as:"
echo "   - PNG format"
echo "   - In docs/screenshots/ directory"
echo "   - Descriptive filenames (main-window.png, add-project.png, etc.)"
echo ""
echo "6. 🔧 For animated GIFs:"
echo "   - Use tools like LICEcap, Kap, or byzanz"
echo "   - Show: opening the app, adding a project, opening a project"
echo "   - Keep file size under 2MB"
echo "   - Duration: 10-15 seconds max"
echo ""
echo "7. ✅ Update README.md with new screenshots"
echo ""
echo "Example screenshot workflow:"
echo "  mkdir -p docs/screenshots"
echo "  # Take screenshots"
echo "  # Then update README.md image links"
echo ""
echo "Need help? Check the CONTRIBUTING.md file or open an issue!"

# Create screenshots directory if it doesn't exist
mkdir -p docs/screenshots

echo ""
echo "✨ Screenshots directory created at: docs/screenshots/"
