name: Build and Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Neutralino CLI
        run: npm install -g @neutralinojs/neu

      - name: Update Neutralino binaries
        run: neu update

      - name: Build application
        run: neu build

      - name: Prepare release assets
        run: |
          mkdir -p release-assets

          # Copy binaries with proper names
          cp dist/dev-monitor/dev-monitor-linux_x64 release-assets/dev-monitor-linux-x64
          cp dist/dev-monitor/dev-monitor-linux_arm64 release-assets/dev-monitor-linux-arm64
          cp dist/dev-monitor/dev-monitor-linux_armhf release-assets/dev-monitor-linux-armhf
          cp dist/dev-monitor/dev-monitor-mac_x64 release-assets/dev-monitor-mac-x64
          cp dist/dev-monitor/dev-monitor-mac_arm64 release-assets/dev-monitor-mac-arm64
          cp dist/dev-monitor/dev-monitor-mac_universal release-assets/dev-monitor-mac-universal
          cp dist/dev-monitor/dev-monitor-win_x64.exe release-assets/dev-monitor-win-x64.exe

          # Copy the resources.neu file (contains all app resources)
          cp dist/dev-monitor/resources.neu release-assets/resources.neu

          # Make Linux/macOS binaries executable
          chmod +x release-assets/dev-monitor-linux-*
          chmod +x release-assets/dev-monitor-mac-*

          # Create checksums for verification
          cd release-assets
          sha256sum * > checksums.txt
          cd ..

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} \
            --title "Release ${{ github.ref_name }}" \
            --notes "## Changes in this Release
          - Bug fixes and improvements
          - Cross-platform binaries for Linux, macOS, and Windows

          ## Installation

          ### Quick Install (Linux/macOS)
          \`\`\`bash
          curl -sSL https://raw.githubusercontent.com/${{ github.repository }}/main/install.sh | bash
          \`\`\`

          ### Quick Install (Windows)
          \`\`\`powershell
          iwr -useb https://raw.githubusercontent.com/${{ github.repository }}/main/install.ps1 | iex
          \`\`\`

          ### Manual Download
          Download the appropriate binary for your platform below and make it executable." \
            release-assets/*
